const express = require("express");
const cors = require("cors");

const app = express();

app.use(express.json());
app.use(cors());

const students= [
    {
      firstName: "שרה",
      lastName: "לוי",
      id: 305493284,
      dateOfBirth: new Date("03/25/2000"),
      phoneNumber: 5026637201,
      emailAddress: "fake@gmail.com",
      Theory: false,
      numberOfLessons: 3,
      testDate: new Date(),
      pricePerLesson: 140,
      internalTest: false,
      registrationFees: true,
      enteredSchool: true,
      //   debt: false,
      payment: 280,
    },
    {
      firstName: "חיה",
      lastName: "כהן",
      id: 305233284,
      dateOfBirth: new Date("03/25/2000"),
      phoneNumber: 5026637201,
      emailAddress: "fake@gmail.com",
      Theory: false,
      numberOfLessons: 3,
      testDate: new Date(),
      pricePerLesson: 140,
      internalTest: false,
      registrationFees: true,
      enteredSchool: true,
      //   debt: false,
      payment: 280,
    },
    {
      firstName: "נועה",
      lastName: "דגן",
      id: 305494284,
      dateOfBirth: new Date("03/25/2000"),
      phoneNumber: 5026637201,
      emailAddress: "fake@gmail.com",
      Theory: false,
      numberOfLessons: 3,
      testDate: new Date(),
      pricePerLesson: 140,
      internalTest: false,
      registrationFees: true,
      enteredSchool: true,
      //   debt: false,
      payment: 280,
    },
    {
      firstName: "שרה",
      lastName: "לוי",
      id: 305493286,
      dateOfBirth: new Date("03/25/2000"),
      phoneNumber: 5026637201,
      emailAddress: "fake@gmail.com",
      Theory: false,
      numberOfLessons: 3,
      testDate: new Date(),
      pricePerLesson: 140,
      internalTest: false,
      registrationFees: true,
      enteredSchool: true,
      //   debt: false,
      payment: 280,
    },
    {
      firstName: "חיה",
      lastName: "כהן",
      id: 305633284,
      dateOfBirth: new Date("03/25/2000"),
      phoneNumber: 5026637201,
      emailAddress: "fake@gmail.com",
      Theory: false,
      numberOfLessons: 3,
      testDate: new Date(),
      pricePerLesson: 140,
      internalTest: false,
      registrationFees: true,
      enteredSchool: true,
      //   debt: false,
      payment: 280,
    },
    {
      firstName: "נועה",
      lastName: "דגן",
      id: 305496284,
      dateOfBirth: new Date("03/25/2000"),
      phoneNumber: 5026637201,
      emailAddress: "fake@gmail.com",
      Theory: false,
      numberOfLessons: 3,
      testDate: new Date(),
      pricePerLesson: 140,
      internalTest: false,
      registrationFees: true,
      enteredSchool: true,
      //   debt: false,
      payment: 280,
    },
    {
      firstName: "שרה",
      lastName: "לוי",
      id: 315493284,
      dateOfBirth: new Date("03/25/2000"),
      phoneNumber: 5026637201,
      emailAddress: "fake@gmail.com",
      Theory: false,
      numberOfLessons: 3,
      testDate: new Date(),
      pricePerLesson: 140,
      internalTest: false,
      registrationFees: true,
      enteredSchool: true,
      //   debt: false,
      payment: 280,
    },
    {
      firstName: "חיה",
      lastName: "כהן",
      id: 305234284,
      dateOfBirth: new Date("03/25/2000"),
      phoneNumber: 5026637201,
      emailAddress: "fake@gmail.com",
      Theory: false,
      numberOfLessons: 3,
      testDate: new Date(),
      pricePerLesson: 140,
      internalTest: false,
      registrationFees: true,
      enteredSchool: true,
      //   debt: false,
      payment: 280,
    },
    {
      firstName: "נועה",
      lastName: "דגן",
      id: 305394284,
      dateOfBirth: new Date("03/25/2000"),
      phoneNumber: 5026637201,
      emailAddress: "fake@gmail.com",
      Theory: false,
      numberOfLessons: 3,
      testDate: new Date(),
      pricePerLesson: 140,
      internalTest: false,
      registrationFees: true,
      enteredSchool: true,
      //   debt: false,
      payment: 280,
    },
    {
      firstName: "שרה",
      lastName: "לוי",
      id: 305293284,
      dateOfBirth: new Date("03/25/2000"),
      phoneNumber: 5026637201,
      emailAddress: "fake@gmail.com",
      Theory: false,
      numberOfLessons: 3,
      testDate: new Date(),
      pricePerLesson: 140,
      internalTest: false,
      registrationFees: true,
      enteredSchool: true,
      //   debt: false,
      payment: 280,
    },
    {
      firstName: "חיה",
      lastName: "כהן",
      id: 305233214,
      dateOfBirth: new Date("03/25/2000"),
      phoneNumber: 5026637201,
      emailAddress: "fake@gmail.com",
      Theory: false,
      numberOfLessons: 3,
      testDate: new Date(),
      pricePerLesson: 140,
      internalTest: false,
      registrationFees: true,
      enteredSchool: true,
      //   debt: false,
      payment: 280,
    },
    {
      firstName: "נועה",
      lastName: "דגן",
      id: 305494184,
      dateOfBirth: new Date("03/25/2000"),
      phoneNumber: 5026637201,
      emailAddress: "fake@gmail.com",
      Theory: false,
      numberOfLessons: 3,
      testDate: new Date(),
      pricePerLesson: 140,
      internalTest: false,
      registrationFees: true,
      enteredSchool: true,
      //   debt: false,
      payment: 280,
    },
  ];
app.get("/students", async(req, res) => {
    const { q } = req.query;
    if (q) {
      res.send(students.filter((student) => student.name.includes(q)));
    } else {
      res.send(students);
    }
  });

  app.listen(8000, () => {
    console.log("Example app listening on port 8000!");
  });